import { Exercise } from '@/types';

export const exercisesList: Array<Exercise> = [
  {
    title: 'Agachamento unilateral barra guiada',
    series: 3,
    intervalSeconds: 45,
    videoUrl: '/videos/agachamento.mp4',
    previewImgUrl: '/previews/preview.jpg',
    minReps: 12,
    maxReps: 15,
  },
  {
    title: 'Cadeira extensora 2 tempos',
    series: 3,
    intervalSeconds: 45,
    videoUrl: '/videos/extensora.mp4',
    previewImgUrl: '/previews/preview-3.jpg',
    minReps: 12,
    maxReps: 15,
  },
  {
    title: 'Flexão quadril polia',
    series: 3,
    intervalSeconds: 45,
    videoUrl: '/videos/flex_quadril_polia.mp4',
    previewImgUrl: '/previews/preview-2.jpg',
    minReps: 12,
    maxReps: 15,
  },
  {
    title: 'Rotação externa polia',
    series: 3,
    intervalSeconds: 45,
    videoUrl: '/videos/rotacao_externa_polia.mp4',
    previewImgUrl: '/previews/preview-1.jpg',
    minReps: 12,
    maxReps: 15,
  },
  // {
  //   title: 'Remada inclinada aberta livre pronada',
  //   series: 3,
  //   intervalSeconds: 45,
  //   videoUrl: 'remada_inclinada_aberta_livre_pronada.mp4',
  //   previewImgUrl: '/previews/preview2.jpg',
  //   minReps: 12,
  //   maxReps: 15,
  // },
  // {
  //   title: 'Cricifixo inverso + elevação halter banco',
  //   series: 3,
  //   intervalSeconds: 45,
  //   videoUrl: 'cruc_inverso_elevacao_halter_banco.mp4',
  //   previewImgUrl: '/previews/preview3.jpg',
  //   minReps: 12,
  //   maxReps: 15,
  // },
  // {
  //   title: 'Abdominal twist russo no bosu',
  //   series: 3,
  //   intervalSeconds: 45,
  //   videoUrl: 'ab_twist_russo_bosu.mp4',
  //   previewImgUrl: '/previews/preview.jpg',
  //   minReps: 20,
  //   maxReps: 30,
  // },
  // {
  //   title: 'Perdigueiro',
  //   series: 3,
  //   intervalSeconds: 45,
  //   videoUrl: 'perdigueiro.mp4',
  //   previewImgUrl: '/previews/preview2.jpg',
  //   minReps: 20,
  //   maxReps: 30,
  // },
  // {
  //   title: 'Ponte lateral',
  //   series: 3,
  //   intervalSeconds: 45,
  //   videoUrl: 'ponte_lateral.mp4',
  //   previewImgUrl: '/previews/preview3.jpg',
  //   minReps: 1,
  // },
];
